import { useEffect, useState } from 'react'
import api, { apiErrorMessage } from '../lib/api'
import toast from 'react-hot-toast'
import { ArrowLeft, Loader2 } from 'lucide-react'

export default function ForgotPassword() {
  const [step, setStep] = useState<1 | 2 | 3 | 4>(1), [email, setEmail] = useState(''), [otp, setOtp] = useState(''), [resetToken, setResetToken] = useState(''), [password, setPassword] = useState(''), [confirm, setConfirm] = useState(''), [loading, setLoading] = useState(false), [cooldown, setCooldown] = useState(0)
  useEffect(() => { if (!cooldown) return; const t = window.setInterval(() => setCooldown(v => v - 1), 1000); return () => clearInterval(t) }, [cooldown])
  const send = async () => { setLoading(true); try { await api.post('/auth/forgot-password', { email }); setStep(2); setCooldown(30); toast.success('OTP has been sent to your registered email.') } catch (e) { toast.error(apiErrorMessage(e, 'Unable to send OTP email. Please try again.')) } finally { setLoading(false) } }
  const verify = async () => { setLoading(true); try { const r = await api.post('/auth/verify-reset-otp', { email, otp }); setResetToken(r.data.reset_token); setStep(3); toast.success('OTP verified successfully') } catch (e) { toast.error(apiErrorMessage(e, 'Invalid OTP')) } finally { setLoading(false) } }
  const reset = async () => { if (password !== confirm) return toast.error('Passwords do not match'); setLoading(true); try { await api.post('/auth/reset-password', { reset_token: resetToken, new_password: password, confirm_password: confirm }); setStep(4); toast.success('Password changed successfully') } catch (e) { toast.error(apiErrorMessage(e, 'Unable to change password')) } finally { setLoading(false) } }
  return <div className="min-h-screen flex items-center justify-center p-4 bg-gradient-to-br from-primary-50 via-white to-indigo-50 dark:from-gray-950 dark:via-gray-900 dark:to-gray-950"><div className="w-full max-w-md card p-8"><a href="/login" className="inline-flex items-center gap-1 text-sm text-gray-400 mb-4"><ArrowLeft size={14} /> Back to login</a><h1 className="text-2xl font-bold">Forgot Password</h1><p className="text-sm text-gray-500 mb-6">{step === 1 ? 'Enter your registered email to receive an OTP.' : step === 2 ? 'Enter the six-digit OTP from your email. It expires in 5 minutes.' : step === 3 ? 'Create a new password for your account.' : 'Your password has been changed.'}</p>
    {step === 1 && <form onSubmit={e => { e.preventDefault(); void send() }} className="space-y-4"><input className="input" required type="email" placeholder="Registered email" value={email} onChange={e => setEmail(e.target.value)} /><button className="btn-primary w-full" disabled={loading}>{loading ? <Loader2 className="animate-spin mx-auto" size={16} /> : 'Send OTP'}</button></form>}
    {step === 2 && <div className="space-y-4"><input className="input text-center tracking-[.5em]" inputMode="numeric" maxLength={6} placeholder="______" value={otp} onChange={e => setOtp(e.target.value.replace(/\D/g, ''))} /><button className="btn-primary w-full" disabled={loading || otp.length !== 6} onClick={() => void verify()}>Verify OTP</button><button className="btn-secondary w-full" disabled={loading || cooldown > 0} onClick={() => void send()}>{cooldown ? `Resend OTP in ${cooldown}s` : 'Resend OTP'}</button></div>}
    {step === 3 && <div className="space-y-4"><input className="input" type="password" placeholder="New password (minimum 8 characters)" value={password} onChange={e => setPassword(e.target.value)} /><input className="input" type="password" placeholder="Confirm new password" value={confirm} onChange={e => setConfirm(e.target.value)} /><button className="btn-primary w-full" disabled={loading || password.length < 8} onClick={() => void reset()}>Change Password</button></div>}
    {step === 4 && <a href="/login" className="btn-primary block text-center">Back to Login</a>}</div></div>
}
