import { useEffect, useState } from 'react'
import api, { apiErrorMessage } from '../lib/api'
import { Badge, Card, PageHeader } from '../components/ui'
import toast from 'react-hot-toast'

export default function LeavePage({ role }: { role: 'student' | 'teacher' }) {
  const [rows, setRows] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false)
  const [form, setForm] = useState({ leave_type: 'Sick Leave', from_date: '', to_date: '', reason: '' })
  const load = async () => { setLoading(true); try { setRows((await api.get('/leave/mine')).data) } catch (e) { toast.error(apiErrorMessage(e, 'Unable to load leave requests')) } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  const submit = async (e: React.FormEvent) => { e.preventDefault(); setSaving(true); try { await api.post('/leave', form); toast.success('Leave request submitted successfully'); setForm({ leave_type: 'Sick Leave', from_date: '', to_date: '', reason: '' }); await load() } catch (e) { toast.error(apiErrorMessage(e, 'Unable to submit leave request')) } finally { setSaving(false) } }
  const cancel = async (id: number) => { if (!window.confirm('Cancel this pending leave request?')) return; try { await api.post(`/leave/${id}/cancel`); toast.success('Leave request cancelled'); await load() } catch (e) { toast.error(apiErrorMessage(e, 'Unable to cancel leave request')) } }
  const color = (s: string) => s === 'approved' ? 'green' : s === 'rejected' ? 'red' : s === 'cancelled' ? 'gray' : 'yellow'
  return <><PageHeader title="My Leave" subtitle={role === 'teacher' ? 'Apply for leave and track admin review' : 'Apply for leave and track your request'} />
    <Card><form onSubmit={submit} className="grid grid-cols-1 md:grid-cols-2 gap-4"><div><label className="label">Leave Type</label><select className="input" value={form.leave_type} onChange={e => setForm({ ...form, leave_type: e.target.value })}><option>Sick Leave</option><option>Casual Leave</option><option>Emergency Leave</option><option>Other</option></select></div><div><label className="label">From Date</label><input required type="date" className="input" value={form.from_date} onChange={e => setForm({ ...form, from_date: e.target.value })} /></div><div><label className="label">To Date</label><input required type="date" className="input" value={form.to_date} min={form.from_date} onChange={e => setForm({ ...form, to_date: e.target.value })} /></div><div className="md:col-span-2"><label className="label">Reason</label><textarea required className="input min-h-24" value={form.reason} onChange={e => setForm({ ...form, reason: e.target.value })} /></div><button disabled={saving} className="btn-primary w-fit">{saving ? 'Submitting…' : 'Submit Leave Request'}</button></form></Card>
    <div className="mt-6"><h2 className="text-lg font-semibold mb-3">My Leave Requests</h2><Card>{loading ? <p>Loading…</p> : rows.length === 0 ? <p className="text-gray-500">No leave requests yet.</p> : <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left border-b"><th className="p-2">Type</th><th className="p-2">Dates</th><th className="p-2">Days</th><th className="p-2">Reason</th><th className="p-2">Status</th><th className="p-2">Review</th><th className="p-2"></th></tr></thead><tbody>{rows.map(r => <tr key={r.id} className="border-b"><td className="p-2">{r.leave_type}</td><td className="p-2">{r.from_date} – {r.to_date}</td><td className="p-2">{r.days}</td><td className="p-2">{r.reason}{r.rejection_reason && <div className="text-red-600">{r.rejection_reason}</div>}</td><td className="p-2"><Badge variant={color(r.status) as any}>{r.status}</Badge></td><td className="p-2">{r.reviewer || '—'} {r.reviewed_at && new Date(r.reviewed_at).toLocaleDateString()}</td><td className="p-2">{r.status === 'pending' && <button className="text-red-600" onClick={() => cancel(r.id)}>Cancel</button>}</td></tr>)}</tbody></table></div>}</Card></div></>
}
